### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by grezniczek** [jangari/redcap_hidesubmit#6]
https://github.com/jangari/redcap_hidesubmit/blob/24b22cf68de9a4126431b46b0c1cd16926be7fc9/HideSubmit.php#L51

Change the class name to `\INTERSECT\HideSubmit\ActionTagHelper` here (or simply to `ActionTagHelper`, which should look in the current namespace and work, too).

**Comment by jangari** [comment]
Thanks @grezniczek, I haven't worked much with classes, so mistakes are to be expected!
